title: Alik Khilazhev's blog
email: alikhil@mail.ru
description: > # this means to ignore newlines until "github_username:"
  Insights, hacks, tutorials and other things which were discovered by me.
github_username:  alikhil
theme: jekyll-theme-hacker
future: true
markdown: kramdown
# twitter_username: jekyllrb
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alikhil.github.io" # the base hostname & protocol for your site, e.g. http://example.com
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty